server.port=${SERVER_PORT:8080}

# H2 Database (development)
#spring.datasource.url=jdbc:h2:file:./data/dailydb;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dailydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}


# CORS - Ajuste para o IP da rede interna
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://192.168.1.0/24,http://10.10.51.188:4200,http://10.10.51.188/24}

# JWT
app.jwt.secret=${APP_JWT_SECRET:SuaChaveSecretaMuitoSeguraParaJWTDailySystem2024}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# Logging
logging.level.com.daily=INFO
